name: nachtmeister
favicon: null
layout_spectrum: 0.5673900782130659
typography_spectrum: 0.9268299243412912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e33'
    - '#9d153f'
    - '#934632'
    - '#d4745d'
    - '#fdcbbb'
  brandStrength: 0.919004293391481
  lightness: 0
  saturation: 0.8393948685843498
  rhythmicContrast: 0.5
purpose: []
